### ISSUE TITLE
Stickyness in Listener Rule, not just Target Group

### ISSUE THREAD

**Issue by joshgubler** [byu-oit/terraform-aws-fargate-api#45]
I think AWS must have changed this behavior recently. CAS is getting [the following error](https://github.com/byu-oit/cas5/actions/runs/6592984354/job/17914676543#step:19:105):
> InvalidLoadBalancerAction: You must enable group stickiness on a rule if you enabled target stickiness on one of its target groups

I think this means that we need to (conditionally) add the stickiness block [to the listener](https://github.com/byu-oit/terraform-aws-fargate-api/blob/6a8b5fc35ed94c1ef0885afa36f52dd8144e7ca8/main.tf#L251-L260), similar to the way we add it [to the target group](https://github.com/byu-oit/terraform-aws-fargate-api/blob/6a8b5fc35ed94c1ef0885afa36f52dd8144e7ca8/main.tf#L203-L206). 

Here is the [Terraform doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener) that describes what the stickiness block should look like. We probably need to expose `duration` as a variable.

**Comment by joshgubler** [comment]
Apparently, for the target group, we just accept the [default value of 1 day](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#cookie_duration), and don't expose a variable to override that default. Maybe we should just hard code that default value in for the listener for now.

**Comment by joshgubler** [comment]
If we do make this change, we need to do some testing to ensure that the stickiness doesn't break clients during a deploy when the weight on the previous "stuck" target group gets set to 0.

**Comment by jvisker** [comment]
Should be fixed in 6.0.1
